# Generated by Django 5.1.1 on 2025-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
